---
development:
  cloud_name: dqlhjjbku
  api_key: '837654161211597'
  api_secret: 9LdiDL61eVgKkoQBX3PeqKpLor8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dqlhjjbku
  api_key: '837654161211597'
  api_secret: 9LdiDL61eVgKkoQBX3PeqKpLor8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dqlhjjbku
  api_key: '837654161211597'
  api_secret: 9LdiDL61eVgKkoQBX3PeqKpLor8
  enhance_image_tag: true
  static_image_support: false
